site:
  name: VarsCalculator
  site: 'https://aboutsvc.github.io/vars-calculator-web-v2'
  base: '/vars-calculator-web-v2'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: VarsCalculator
    template: '%s — VarsCalculator'
  description: "Simplify your calculations with custom variable expressions. Save formulas, calculate instantly with variables X, Y, Z, and boost productivity. Perfect for students, professionals, and businesses. Download now for smarter math solutions!"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: VarsCalculator
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
